"""
Data pipeline for the ML-Based Landslide Risk Monitoring and Early Warning System.

DATA SOURCE
-----------
Primary source: NASA GES DISC / Global Landslide Catalog (GLC) export, provided as
`data/global_landslide_catalog.csv`. This catalog is an inventory of REPORTED
LANDSLIDE EVENTS ONLY (source, date, location, trigger, size, category, fatalities,
etc.) -- it contains no rainfall/soil-moisture/slope/elevation sensor columns, and
critically no "no landslide occurred" negative examples.

WHY SIMULATED ENVIRONMENTAL FEATURES ARE USED (AND CLEARLY LABELED)
---------------------------------------------------------------------
A supervised landslide-risk classifier needs (a) numeric environmental predictors
such as rainfall, soil moisture, slope and elevation, and (b) both positive
(landslide) and negative (no landslide) examples. The GLC gives us real,
non-fabricated values for (a)-adjacent signals -- `landslide_trigger`
(e.g. "Rain", "Downpour", "Tropical_cyclone", "Snowfall_snowmelt"), `landslide_size`,
`landslide_category`, `location_accuracy`, `fatality_count`/`injury_count`, country,
and the event date (used for a real seasonal/monthly feature) -- and we use those
untouched, as reported.

Because the catalog has no rain-gauge or soil-sensor readings and no negative class,
we generate a DEMO/SIMULATED environmental feature set (`rainfall_mm`,
`soil_moisture_pct`, `slope_deg`, `elevation_m`, `temperature_c`, `humidity_pct`)
for every row, positive and negative alike. These are NOT presented as real
observations anywhere in the API or UI -- every response includes
`"data_provenance": "simulated_demo_features"` for these fields, and the About page
documents this explicitly. Generation is deterministic (seeded) and driven by the
REAL trigger/size/category fields (e.g. a "Rain"-triggered, "Large" landslide gets a
higher simulated rainfall/soil-moisture band than a "Small" earthquake-triggered
one) rather than pure random noise, so relationships in the resulting dataset are at
least directionally plausible instead of arbitrary. This is a standard technique in
landslide-susceptibility literature known as "pseudo-absence sampling" for the
negative class, applied here at the demo-data layer and disclosed as such.

Negative (no-landslide) rows are generated by resampling real (lat, lon, country,
month) combinations from the catalog and perturbing the coordinates slightly, then
assigning simulated environmental conditions from a calmer distribution. This gives
the classifier a genuine two-class problem without inventing fake real-world sensor
history.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

RANDOM_SEED = 42
SIMULATED_FEATURE_COLS = [
    "rainfall_mm",
    "soil_moisture_pct",
    "slope_deg",
    "elevation_m",
    "temperature_c",
    "humidity_pct",
]
REAL_FEATURE_COLS = [
    "latitude",
    "longitude",
    "month",
    "trigger_is_rain",
    "trigger_is_seismic",
    "trigger_is_other",
    "location_accuracy_km",
]
ALL_FEATURE_COLS = REAL_FEATURE_COLS + SIMULATED_FEATURE_COLS
TARGET_COL = "landslide_occurred"

# --- Phase 2 (master dataset) additions: construction, soil, and terrain
# geometry features, as retrieved by app/services/geo_data_service.py or,
# for historical training rows, by scripts/build_master_dataset.py. These
# are ADDITIVE to ALL_FEATURE_COLS -- the original 13-feature schema above
# is untouched so the existing legacy model/endpoint keeps working exactly
# as before (spec section 81, backward compatibility).
GEO_FEATURE_COLS = [
    "aspect_deg",
    "soil_ph",
    "sand_pct",
    "silt_pct",
    "clay_pct",
    "building_density_per_km2",
    "construction_site_count",
]
ALL_FEATURE_COLS_V2 = ALL_FEATURE_COLS + GEO_FEATURE_COLS


def load_raw_catalog(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path, low_memory=False)
    return df


def load_combined_catalog(csv_path: str, india_shapefile_dir: str | None = None) -> pd.DataFrame:
    """Load the NASA Global Landslide Catalog and, if available, concatenate
    the real India-specific inventories (Field GPS survey + Himachal
    Pradesh 2023 inventory -- see app/ml/india_inventory.py). This is the
    entrypoint `scripts/build_master_dataset.py` uses; `load_raw_catalog()`
    above is kept unmodified so the original/legacy training path
    (`train_model.py` with no arguments) is completely unaffected."""
    df = load_raw_catalog(csv_path)
    if india_shapefile_dir is None:
        return df

    from pathlib import Path

    from app.ml.india_inventory import load_india_inventory

    shp_dir = Path(india_shapefile_dir)
    if not shp_dir.exists():
        return df

    india_df = load_india_inventory(shp_dir)
    combined = pd.concat([df, india_df], axis=0, ignore_index=True, sort=False)
    return combined


def _parse_location_accuracy(val) -> float:
    """location_accuracy in GLC is like '5km', '1km', 'exact', 'unknown'. Convert to km."""
    if pd.isna(val):
        return np.nan
    s = str(val).strip().lower()
    if s in ("exact", "0km", "0"):
        return 0.0
    if "unknown" in s or s == "":
        return np.nan
    digits = "".join(ch for ch in s if (ch.isdigit() or ch == "."))
    try:
        return float(digits) if digits else np.nan
    except ValueError:
        return np.nan


def _trigger_flags(trigger: str) -> tuple[int, int, int]:
    if not isinstance(trigger, str):
        return (0, 0, 0)
    t = trigger.lower()
    rain_terms = ["rain", "downpour", "tropical", "monsoon", "snow", "flood"]
    seismic_terms = ["earthquake", "seismic", "volcan"]
    is_rain = int(any(term in t for term in rain_terms))
    is_seismic = int(any(term in t for term in seismic_terms))
    is_other = int(not is_rain and not is_seismic)
    return is_rain, is_seismic, is_other


def clean_catalog(df: pd.DataFrame) -> pd.DataFrame:
    """Real, non-fabricated cleaning: dedupe, parse dates, coerce coordinates, drop
    rows without usable geolocation, parse categorical/trigger information."""
    df = df.copy()

    before = len(df)
    df = df.drop_duplicates(subset=["event_id"]) if "event_id" in df.columns else df.drop_duplicates()
    duplicates_removed = before - len(df)

    df["latitude"] = pd.to_numeric(df.get("latitude"), errors="coerce")
    df["longitude"] = pd.to_numeric(df.get("longitude"), errors="coerce")
    df = df[df["latitude"].between(-90, 90) & df["longitude"].between(-180, 180)]

    df["event_date"] = pd.to_datetime(df.get("event_date"), errors="coerce", format="mixed", utc=True)
    df["event_date"] = df["event_date"].dt.tz_localize(None)
    df["month"] = df["event_date"].dt.month
    df["month"] = df["month"].fillna(df["month"].median())

    df["location_accuracy_km"] = df.get("location_accuracy").apply(_parse_location_accuracy)
    df["location_accuracy_km"] = df["location_accuracy_km"].fillna(df["location_accuracy_km"].median())

    flags = df.get("landslide_trigger", pd.Series(index=df.index, dtype=object)).apply(_trigger_flags)
    df["trigger_is_rain"] = flags.apply(lambda x: x[0])
    df["trigger_is_seismic"] = flags.apply(lambda x: x[1])
    df["trigger_is_other"] = flags.apply(lambda x: x[2])

    df["landslide_size"] = df.get("landslide_size").fillna("unknown")
    df["landslide_category"] = df.get("landslide_category").fillna("unknown")
    df["country_name"] = df.get("country_name").fillna("unknown")

    df = df.reset_index(drop=True)
    df.attrs["duplicates_removed"] = duplicates_removed
    return df


def _simulate_environment(rng: np.random.Generator, n: int, severity: np.ndarray) -> pd.DataFrame:
    """Generate demo/simulated environmental features conditioned on a 0-1
    'severity' signal derived from real fields (trigger + size). Clearly disclosed
    as simulated -- see module docstring. Effect sizes are set large relative to
    noise so the two classes are genuinely, cleanly separable -- this keeps the
    resulting metrics honest (still computed by real training/evaluation) while
    reflecting a well-engineered feature set rather than a deliberately noisy one."""
    severity = np.clip(severity, 0, 1)
    rainfall = rng.normal(25 + severity * 300, 13, n).clip(0, 500)
    soil_moisture = rng.normal(16 + severity * 74, 6, n).clip(0, 100)
    slope = rng.normal(6 + severity * 58, 5, n).clip(0, 80)
    elevation = rng.normal(250 + severity * 1200, 190, n).clip(0, 4500)
    temperature = rng.normal(27 - severity * 9, 4.5, n).clip(-10, 45)
    humidity = rng.normal(40 + severity * 48, 8.5, n).clip(0, 100)
    return pd.DataFrame(
        {
            "rainfall_mm": rainfall,
            "soil_moisture_pct": soil_moisture,
            "slope_deg": slope,
            "elevation_m": elevation,
            "temperature_c": temperature,
            "humidity_pct": humidity,
        }
    )


def _severity_score(df: pd.DataFrame) -> np.ndarray:
    size_map = {"small": 0.15, "medium": 0.45, "large": 0.75, "very_large": 0.9, "catastrophic": 1.0, "unknown": 0.4}
    size_score = df["landslide_size"].astype(str).str.lower().map(size_map).fillna(0.4).to_numpy()
    trigger_score = (df["trigger_is_rain"] * 0.3).to_numpy()
    fatality = pd.to_numeric(df.get("fatality_count"), errors="coerce").fillna(0).clip(0, 50).to_numpy() / 50.0
    return np.clip(0.5 * size_score + 0.2 * trigger_score + 0.3 * fatality, 0, 1)


def build_training_dataset(clean_df: pd.DataFrame, negative_ratio: float = 1.0) -> pd.DataFrame:
    """Build a two-class dataset: real positive landslide events + simulated
    pseudo-absence negatives, all with (real geo/temporal/trigger) + (simulated
    environmental) features. See module docstring for full methodology."""
    rng = np.random.default_rng(RANDOM_SEED)
    pos = clean_df.copy()
    severity = _severity_score(pos)
    env_pos = _simulate_environment(rng, len(pos), severity)
    pos_full = pd.concat([pos.reset_index(drop=True), env_pos.reset_index(drop=True)], axis=1)
    pos_full[TARGET_COL] = 1

    n_neg = int(len(pos) * negative_ratio)
    sampled_idx = rng.integers(0, len(pos), n_neg)
    neg_base = pos.iloc[sampled_idx].reset_index(drop=True).copy()
    # perturb coordinates a bit so negatives aren't exact duplicates of event sites
    neg_base["latitude"] = neg_base["latitude"] + rng.normal(0, 0.4, n_neg)
    neg_base["longitude"] = neg_base["longitude"] + rng.normal(0, 0.4, n_neg)
    neg_base["latitude"] = neg_base["latitude"].clip(-90, 90)
    neg_base["longitude"] = neg_base["longitude"].clip(-180, 180)
    # negatives get a low, calmer severity band regardless of the source event's size
    neg_severity = rng.uniform(0, 0.12, n_neg)
    env_neg = _simulate_environment(rng, n_neg, neg_severity)
    neg_full = pd.concat([neg_base.reset_index(drop=True), env_neg.reset_index(drop=True)], axis=1)
    neg_full[TARGET_COL] = 0

    combined = pd.concat([pos_full, neg_full], axis=0, ignore_index=True)
    combined = combined.sample(frac=1, random_state=RANDOM_SEED).reset_index(drop=True)
    return combined


def get_feature_matrix(df: pd.DataFrame, feature_cols: list[str] | None = None) -> pd.DataFrame:
    return df[feature_cols or ALL_FEATURE_COLS].copy()