import React from "react";
import { motion } from "framer-motion";
import { ScrollText, ShieldAlert } from "lucide-react";
import Seo from "../components/Seo.jsx";
import PublicPageShell from "../components/PublicPageShell.jsx";

function Section({ number, title, children }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-60px" }}
      transition={{ duration: 0.5 }}
      className="group relative mb-8 pl-14 last:mb-0"
    >
      <div className="absolute left-0 top-0 flex h-9 w-9 items-center justify-center rounded-xl border border-accent-cyan/30 bg-accent-cyan/10 text-sm font-bold text-accent-cyan shadow-glow transition-transform duration-300 group-hover:scale-110">
        {number}
      </div>
      <h2 className="text-base font-semibold text-slate-100 sm:text-lg">
        {title}
      </h2>
      <div className="mt-2 space-y-3 text-sm leading-relaxed text-slate-400">
        {children}
      </div>
    </motion.div>
  );
}

export default function Terms() {
  return (
    <PublicPageShell
      icon={ScrollText}
      eyebrow="Legal"
      title="Terms & Conditions"
      subtitle="Please read these terms carefully before using TerraSense AI."
    >
      <Seo description="TerraSense AI Terms & Conditions." />

      <div className="mb-8 flex items-center gap-3 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs leading-relaxed text-amber-200/90">
        <ShieldAlert className="h-5 w-5 shrink-0 text-amber-400" />
        TerraSense AI is a software-based risk intelligence platform and is
        <strong className="px-1">not a certified emergency-warning service</strong>.
        Always follow official guidance from local disaster-management
        authorities.
      </div>

      <Section number="1" title="About This Platform">
        <p>
          TerraSense AI is an independent, software-based risk intelligence
          platform that combines machine learning, remote sensing, and
          geospatial analysis to estimate landslide risk for a given
          location. It is an academic / independent software project.
        </p>
      </Section>

      <Section number="2" title="No Guarantee of Accuracy">
        <p>
          Predictions, risk scores, and alerts generated by TerraSense AI
          are statistical estimates produced by machine-learning models
          trained on historical data and live environmental sources. They
          are provided for informational and educational purposes only and
          must not be treated as a substitute for official warnings issued
          by government or disaster-management authorities.
        </p>
        <p>
          We do not guarantee the accuracy, completeness, or timeliness of
          any prediction, alert, or piece of environmental data shown on
          the platform. Third-party data sources (weather, elevation,
          soil, geospatial context) may occasionally be delayed,
          incomplete, or temporarily unavailable.
        </p>
      </Section>

      <Section number="3" title="Eligibility & Account Registration">
        <p>
          You must provide accurate information when creating an account,
          including whether you are registering as an individual or on
          behalf of an organization / agency. You are responsible for
          maintaining the confidentiality of your login credentials and
          for all activity that occurs under your account.
        </p>
      </Section>

      <Section number="4" title="Acceptable Use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Attempt to disrupt, overload, or reverse-engineer the platform or its models.</li>
          <li>Use TerraSense AI to generate or distribute misleading public-safety claims.</li>
          <li>Scrape or bulk-extract data from the platform without permission.</li>
          <li>Use the service for any unlawful purpose.</li>
        </ul>
      </Section>

      <Section number="5" title="Data Sources & Estimated Values">
        <p>
          TerraSense AI draws on third-party data sources (weather,
          elevation, soil, and open geospatial datasets). Where real data
          cannot be retrieved for a specific field, the platform may show
          a clearly labeled estimated value rather than leaving that field
          blank — estimated values are never presented as measured or
          live data.
        </p>
      </Section>

      <Section number="6" title="Intellectual Property">
        <p>
          The TerraSense AI name, interface design, and underlying
          software are the property of their respective creators. You may
          not copy, redistribute, or create derivative products from the
          platform without permission.
        </p>
      </Section>

      <Section number="7" title="Limitation of Liability">
        <p>
          To the fullest extent permitted by law, TerraSense AI and its
          creators shall not be liable for any loss, damage, or harm
          arising from reliance on information provided by the platform,
          including decisions made based on a risk prediction or alert.
        </p>
      </Section>

      <Section number="8" title="Termination">
        <p>
          We reserve the right to suspend or terminate accounts that
          violate these Terms, misuse the platform, or attempt to
          compromise its security.
        </p>
      </Section>

      <Section number="9" title="Changes to These Terms">
        <p>
          These Terms may be updated from time to time. Continued use of
          the platform after changes are posted constitutes acceptance of
          the revised Terms.
        </p>
      </Section>

      <Section number="10" title="Contact">
        <p>
          Questions about these Terms can be sent through our{" "}
          <a href="/contact" className="text-accent-cyan hover:underline">
            Contact page
          </a>
          .
        </p>
      </Section>
    </PublicPageShell>
  );
}
