"""initial schema

Revision ID: d3c94052dd14
Revises: 
Create Date: 2026-09-12 08:08:45.320047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c94052dd14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_name', 'locations', ['name'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_type', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dataset_name', sa.String(length=200), nullable=False),
    sa.Column('dataset_version', sa.String(length=120), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('testing_samples', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('artifact_path', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version')
    )
    op.create_index('ix_model_runs_version', 'model_runs', ['model_version'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_email', 'otp_verifications', ['email'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pw_reset_email', 'password_reset_tokens', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('google_sub', sa.String(length=120), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('environmental_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_env_readings_location_id', 'environmental_readings', ['location_id'], unique=False)
    op.create_index('ix_env_readings_timestamp', 'environmental_readings', ['timestamp'], unique=False)
    op.create_table('landslide_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('trigger', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fatality_count', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('dataset_reference', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_landslide_events_event_date', 'landslide_events', ['event_date'], unique=False)
    op.create_index('ix_landslide_events_location_id', 'landslide_events', ['location_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('environmental_reading_id', sa.Integer(), nullable=True),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_class', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('prediction_source', sa.String(length=20), nullable=False),
    sa.Column('input_features', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environmental_reading_id'], ['environmental_readings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_location_id', 'predictions', ['location_id'], unique=False)
    op.create_index('ix_predictions_model_version', 'predictions', ['model_version'], unique=False)
    op.create_index('ix_predictions_risk_level', 'predictions', ['risk_level'], unique=False)
    op.create_index('ix_predictions_timestamp', 'predictions', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('alert_level', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_location_id', 'alerts', ['location_id'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_location_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_predictions_timestamp', table_name='predictions')
    op.drop_index('ix_predictions_risk_level', table_name='predictions')
    op.drop_index('ix_predictions_model_version', table_name='predictions')
    op.drop_index('ix_predictions_location_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_landslide_events_location_id', table_name='landslide_events')
    op.drop_index('ix_landslide_events_event_date', table_name='landslide_events')
    op.drop_table('landslide_events')
    op.drop_index('ix_env_readings_timestamp', table_name='environmental_readings')
    op.drop_index('ix_env_readings_location_id', table_name='environmental_readings')
    op.drop_table('environmental_readings')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_pw_reset_email', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_otp_email', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index('ix_model_runs_version', table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index('ix_locations_name', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
